data:
  container_name: data
  build: mysql/.
mysqldb:
  container_name: mysqldb
  image: mysql:5.6
  environment:
   - MYSQL_ROOT_PASSWORD=secret123
  volumes:
   - "./mysql/fms.sql:/docker-entrypoint-initdb.d/fms.sql"
  volumes_from:
   - data
