phpmyadmin:
  container_name: phpmyadmin
  image: clelanda/phpmyadmin
  environment:
   - MYSQL_USERNAME=root
  external_links:
   - mysqldb:mysql
  ports:
   - "8079:80"
goserver:
  container_name: goserver
  build: server
  ports:
   - "8080:8080"
   - "8081:8081"
  external_links:
   - mysqldb:fms_db
nginx:
  container_name: nginx
  build: .
  ports:
   - "80:80"
   - "443:443"
  links:
   - phpmyadmin:phpmyadmin
   - goserver:goserver
