mysqldb:
  image: mysql/mysql-server:5.6
  environment:
   - MYSQL_ROOT_PASSWORD=secret123
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  environment:
   - MYSQL_USERNAME=root
  links:
   - mysqldb:mysql
  ports:
   - "80"
goserver:
  build: server
  ports:
   - "8080:8080"
   - "8081:8081"
  links:
   - mysqldb:fms_db
nginx:
  build: .
  ports:
   - "80:80"
   - "443:443"
  links:
   - phpmyadmin:phpmyadmin
   - goserver:goserver